# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: coldnew's blog
subtitle:
description:
author: Yen-Chin, Lee
language: zh_TW
language:
    - zh-tw
    - en

timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://coldnew.github.io
root: /
#permalink: :year/:month-:day-:title/
#permalink: blog/:year/:title/
permalink: :title/
permalink_defaults:
  lang:zh_TW

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  筆記: note
  程式練習: pratice
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
#theme: landscape

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:coldnew/coldnew.github.io.git
  branch: master
- type: git
  repo: git@gitcafe.com:coldnew/coldnew.git
  branch: gitcafe-pages

# Feed
feed:
  type: rss2
  path: rss.xml
  limit: 20

# Highlight js
highlight:
  enable: false
  line_number: false

marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: false
  breaks: false
  smartLists: false
  smartypants: false

# For backward compability
alias:
  blog/2012/12/15_2b30d.html: blog/2012/12-15_2b30d
  blog/2012/12/15_636b2.html: blog/2012/12-15_636b2
  blog/2012/12/15_6842d.html: blog/2012/12-15_6842d
  blog/2013/01/12_f11d3.html: blog/2013/01-12_f11d3
  blog/2013/01/27_3c2c1.html: blog/2013/01-27_3c2c1
  blog/2013/03/09_4add8.html: blog/2013/03-09_4add8
  blog/2013/03/20_17398.html: blog/2013/03-20_17398
  blog/2013/04/12_64cf9.html: blog/2013/04-12_64cf9
  blog/2013/04/13_e8542.html: blog/2013/04-13_e8542
  blog/2013/04/25_52838.html: blog/2013/04-25_52838
  blog/2013/05/06_70d34.html: blog/2013/05-06_70d34
  blog/2013/05/20_5cbb7.html: blog/2013/05-20_5cbb7
  blog/2013/06/04_8dbcf.html: blog/2013/06-04_8dbcf
  blog/2013/06/12_848d7.html: blog/2013/06-12_848d7
  blog/2013/06/13_bcb0f.html: blog/2013/06-13_bcb0f
  blog/2013/06/16_d67d4.html: blog/2013/06-16_d67d4
  blog/2013/06/17_234c8.html: blog/2013/06-17_234c8
  blog/2013/06/19_e5bcf.html: blog/2013/06-19_e5bcf
  blog/2013/06/27_1aced.html: blog/2013/06-27_1aced
  blog/2013/06/27_dc09c.html: blog/2013/06-27_dc09c
  blog/2013/06/29_82531.html: blog/2013/06-29_82531
  blog/2013/06/29_dafa8.html: blog/2013/06-29_dafa8
  blog/2013/06/29_edb49.html: blog/2013/06-29_edb49
  blog/2013/06/30_ec7b6.html: blog/2013/06-30_ec7b6
  blog/2013/07/06_a7b2d.html: blog/2013/07-06_a7b2d
  blog/2013/07/13_07e15.html: blog/2013/07-13_07e15
  blog/2013/07/13_5b094.html: blog/2013/07-13_5b094
  blog/2013/07/13_e2ccd.html: blog/2013/07-13_e2ccd
  blog/2013/07/14_a5b3f.html: blog/2013/07-14_a5b3f
  blog/2013/07/19_41f75.html: blog/2013/07-19_41f75
  blog/2013/08/04_9cb53.html: blog/2013/08-04_9cb53
  blog/2013/10/27_46ac36.html: blog/2013/10-27_46ac36
  blog/2013/11/13_1f0563.html: blog/2013/11-13_1f0563
  blog/2013/11/16_d2f3a.html: blog/2013/11-16_d2f3a
  blog/2013/11/18_686_g.html: blog/2013/11-18_686_g
  blog/2013/12/08_c8cab.html: blog/2013/12-08_c8cab
  blog/2013/12/13_b1756.html: blog/2013/12-13_b1756
  blog/2013/12/15_f6961.html: blog/2013/12-15_f6961
  blog/2013/12/17_03349.html: blog/2013/12-17_03349
  blog/2013/12/19_76c4a.html: blog/2013/12-19_76c4a
  blog/2013/12/29_46ac3.html: blog/2013/12-29_46ac3
  blog/2013/12/29_76c4a.html: blog/2013/12-29_76c4a
  blog/2014/01/11_andro.html: blog/2014/01-11_andro
  blog/2014/03/02_614_s.html: blog/2014/03-02_614_s
  blog/2015/05/18_f69644.html: blog/2015/05-18_f69644
  blog/2015/06/08_gp_revolution1.html: blog/2015/06-08_gp_revolution1
  blog/2015/06/09_gp_revolution2.html: blog/2015/06-09_gp_revolution2
  blog/2015/06/09_gp_revolution3.html: blog/2015/06-09_gp_revolution3
  blog/2015/06/10_gp_revolution3_en.html: blog/2015/06-10_gp_revolution3_en
  blog/2015/06/29_clojure4917.html: blog/2015/06-29_clojure4917
  blog/2015/08/17_9cb53.html: blog/2015/08-17_9cb53
  blog/2015/a_brief_view_on_riscv.html: blog/2015/a_brief_view_on_riscv
  blog/2015/building_a_desktop_application_with_cljs_and_electron.html: blog/2015/09-19_cljs_electron
  blog/2015/building_a_desktop_application_with_clojure_and_javafx_webview.html: blog/2015/09-23_clojure_javafx_webview
  blog/2015/busybox_for_riscv_on_qemu.html: blog/2015/busybox_for_riscv_on_qemu
  blog/2015/wandboard_android_4.4.2.html: blog/2015/wandboard_android_4.4.2
  slides/COSCUP2013_org-mode/slide.html: http://coldnew.github.io/COSCUP2013_org-mode/slide.html
  slides/COSCUP2013_org-mode/index.html: http://coldnew.github.io/COSCUP2013_org-mode/slide.html
  slides/org-ioslide: http://coldnew.github.io/org-ioslide
