# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: coldnew&#39;s blog
subtitle:
description:
author: Yen-Chin, Lee
language:
    - zh-tw
    - en

timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://coldnew.github.io
root: /
permalink: :abbrlink/
permalink_defaults:
  lang:zh_TW

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# Category & Tag
default_category: uncategorized
category_map:
  筆記: note
  程式練習: pratice
  zybo board 開發記錄: zybo-board
  emacs 套件介紹: emacs-plugin
  灣區日報閱讀筆記: wanqu-note
  Android Things 學習筆記 (Raspberry Pi 3): android_things_rpi3
  stm32-nucleo 開發紀錄: stm32-nucleo
  演算法筆記: algorithm-note
  演講筆記: tech-talk-note
  i.MX6SoloX SabreSD 學習筆記: imx6sx-sabresd
  DE2-115 開發紀錄: de2-115
  UltraZed-EG PCIe Carrier Card 開發紀錄: ultrazed_3eg_pciecc
  STM32F746 Discovery 開發紀錄: stm32f746g-disco
  電子模組: electronic-modules

tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
#theme: landscape

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:coldnew/coldnew.github.io.git
  branch: master

# Feed
feed:
  type: rss2
  path: rss.xml
  limit: 20
  content:
  content_limit: 140
  order_by: date

# Highlight js
highlight:
  enable: false
  line_number: false

org:
  #emacs: /Applications/Emacs.app/Contents/MacOS/Emacs
  #emacsclient: /Applications/Emacs.app/Contents/MacOS/bin/emacsclient
  cachedir: ./cache/
  user_config: ./emacs/init.el
  clean_cache: true
  htmlize: true
  common: |
    #+OPTIONS: html-postamble:nil num:nil toc:nil ^:nil

abbrlink:
  alg: crc32
  rep: hex

